# Uncomment the next line to define a global platform for your project
  platform :ios, '10.0'

  use_frameworks!

post_install do |installer|
   installer.pods_project.targets.each do |target|
      if target.name == 'RxSwift'
         target.build_configurations.each do |config|
            if config.name == 'Debug'
               config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
            end
         end
      end
   end
end

 target 'TakeItEasy' do
     
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'RxDataSources', '~> 3.0'
    pod 'RxCoreData', '~> 0.4.0'
    pod 'SwiftSpinner', '~> 1.5.0'
    pod 'DatePickerDialog'
    pod 'Action'
    
  end

  target 'TakeItEasyTests' do
    inherit! :search_paths

    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'RxDataSources', '~> 3.0'
    pod 'RxCoreData', '~> 0.4.0'
    pod 'Action'

  end
