# Uncomment the next line to define a global platform for your project
  platform :ios, '10.0'

  use_frameworks!


 target 'TakeItEasy' do
     
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'RxDataSources', '~> 3.0'
    pod 'RxCoreData', '~> 0.4.0'
    pod 'SwiftSpinner'
    pod 'DatePickerDialog'
  end

  target 'TakeItEasyTests' do
    inherit! :search_paths

    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'RxDataSources', '~> 3.0'
    pod 'RxCoreData', '~> 0.4.0'

  end
